# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TUNK_PROJECT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TUNK_PROJECT

  target 'TUNK_PROJECTTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TUNK_PROJECTUITests' do
    # Pods for testing
  end

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'

# Add the pods for any other Firebase products
# For example, to use Firebase Authentication and Cloud Firestore
pod 'Firebase/Auth'
#pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'GoogleSignIn'
pod 'FBSDKLoginKit'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

  pod 'HideShowPasswordTextField', :git => 'https://github.com/Guidebook/HideShowPasswordTextField'
  pod 'SwiftGifOrigin'
  pod 'Alamofire'

end
